name: FitLifeHub
repository: https://github.com/Luis270100/FitLifeHub

packages:
  - .
  - modules/*

command:
  version:
    workspaceChangelog: true
    updateGitTagRefs: true
    linkToCommits: true
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable, though definitely slower.
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  analyze:
    run: cd $MELOS_ROOT_PATH && melos exec -c 1 -- dart analyze . --fatal-infos
    description: Run `flutter analyze` in all packages

  format:
    run: cd $MELOS_ROOT_PATH && melos exec -- "dart format --line-length 80 . --set-exit-if-changed"
    description: Run `flutter format .` in all packages

  test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run all Flutter tests in this project.

  test_coverage:
    description: Merge all packages coverage tracefiles ignoring data related to generated files.
    run: |
      melos exec rm -rf coverage
      melos run test
      melos exec -c 1 --file-exists=coverage/lcov.info -- coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --filters \.g\.dart
      coverde value -i coverage/filtered.lcov.info > MELOS_ROOT_PATH/coverage/result.txt
      genhtml coverage/lcov.info -o coverage/html
      open coverage/html/index.html